version: '2'
services:

  custom_form:
    image: form
    build:
      context: ./
      dockerfile: Dockerfile
    network_mode: host
    restart: always
    volumes:
      - ./dockerScripts:/temp/scripts
    ports:
      - 3000:3000
    depends_on:
      - custom-cassandra
    entrypoint:
      -  /temp/scripts/wait-for-service.sh
      - '0.0.0.0'
      - '9042'
      - 'npm run serve'

  custom-cassandra:
    image: cassandra:latest
    network_mode: host
    restart: always
    expose:
      - 9042
    volumes:
      - /database:/var/lib/cassandra

